import type { Metadata } from "next";
import "./globals.css";
import Menu from "@/components/Menu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Menu />
        <main className="h-screen p-6">
          <h1 className="text-3xl text-center text-white">Widget Meteo</h1>
          <div>
            {
              // les elements retournées par le composant de page.tsx sont dans children
              children
            }
          </div>
        </main>
      </body>
    </html>
  );
}
